import React from "react";

export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    display: "flex",
    flexDirection: "column",
    gap: "1.5rem",
    maxWidth: "800px",
    margin: "0 auto",
  },
  title: {
    fontSize: "1.5rem",
    fontWeight: 700,
    margin: 0,
    color: "#f8fafc",
  },
  subtitle: {
    fontSize: "0.9rem",
    color: "#64748b",
    margin: "-1rem 0 0.5rem 0",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    backgroundColor: "#0f172a",
    border: "1px solid #1e293b",
    borderRadius: "8px",
    padding: "1.5rem",
  },
  textarea: {
    width: "100%",
    height: "300px",
    backgroundColor: "#020617",
    color: "#e2e8f0",
    border: "1px solid #334155",
    borderRadius: "6px",
    padding: "1rem",
    fontSize: "0.95rem",
    fontFamily: "monospace",
    lineHeight: "1.6",
    resize: "vertical",
    outline: "none",
    boxSizing: "border-box",
  },
  buttonRow: {
    display: "flex",
    justifyContent: "flex-end",
  },
  submitButton: {
    backgroundColor: "#10b981",
    color: "#ffffff",
    border: "none",
    padding: "0.75rem 1.5rem",
    borderRadius: "6px",
    fontWeight: 600,
    fontSize: "0.95rem",
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  submitButtonDisabled: {
    backgroundColor: "#1e293b",
    color: "#64748b",
    cursor: "not-allowed",
  },
  centerState: {
    textAlign: "center",
    padding: "4rem 2rem",
    backgroundColor: "#0f172a",
    borderRadius: "12px",
    border: "1px solid #1e293b",
    color: "#94a3b8",
  },
  errorText: {
    color: "#f87171",
    fontSize: "0.9rem",
    margin: "0 0 0.5rem 0",
  },
};