import React from "react";

export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    // 🌟 Force the workspace area to match the exact remaining viewport height
    height: "calc(100vh - 120px)", 
    overflow: "hidden",
  },
  actionBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#0f172a",
    padding: "0.75rem 1.25rem",
    borderRadius: "8px",
    border: "1px solid #1e293b",
    flexShrink: 0, // Prevent header from compressed by flexbox
  },
  titleGroup: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  title: {
    fontSize: "1.2rem",
    fontWeight: 700,
    margin: 0,
    color: "#f8fafc",
  },
  modeBadge: {
    fontSize: "0.72rem",
    backgroundColor: "#1e293b",
    color: "#38bdf8",
    padding: "0.2rem 0.5rem",
    borderRadius: "4px",
    fontWeight: 600,
    border: "1px solid #334155",
  },
  btnGroup: {
    display: "flex",
    gap: "0.75rem",
  },
  buttonSecondary: {
    backgroundColor: "transparent",
    color: "#94a3b8",
    border: "1px solid #334155",
    padding: "0.4rem 0.9rem",
    borderRadius: "6px",
    fontWeight: 600,
    cursor: "pointer",
  },
  buttonPrimary: {
    backgroundColor: "#10b981",
    color: "#ffffff",
    border: "none",
    padding: "0.4rem 1.1rem",
    borderRadius: "6px",
    fontWeight: 600,
    cursor: "pointer",
  },
  buttonAccent: {
    backgroundColor: "#3b82f6",
    color: "#ffffff",
    border: "none",
    padding: "0.4rem 1.1rem",
    borderRadius: "6px",
    fontWeight: 600,
    cursor: "pointer",
  },
  // 🌟 Turn the layout layout into a non-scrolling grid container
  splitLayout: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "1.5rem",
    alignItems: "stretch",
    flex: 1,         // Take up all available vertical space automatically
    minHeight: 0,    // Critical CSS fix to let children inner scrolls work correctly
  },
  // 🌟 Turn individual panels into independent scrollable docks
  panel: {
    backgroundColor: "#0f172a",
    border: "1px solid #1e293b",
    borderRadius: "8px",
    padding: "1.25rem",
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    height: "100%",  // Match the container dynamic height
    boxSizing: "border-box",
  },
  panelTitle: {
    fontSize: "1rem",
    fontWeight: 600,
    color: "#94a3b8",
    margin: 0,
    borderBottom: "1px solid #1e293b",
    paddingBottom: "0.5rem",
    flexShrink: 0,
  },
  // 🌟 Left raw context viewport config
  rawViewer: {
    backgroundColor: "#020617",
    color: "#cbd5e1",
    padding: "1rem",
    borderRadius: "6px",
    fontFamily: "monospace",
    fontSize: "0.9rem",
    whiteSpace: "pre-wrap",
    lineHeight: "1.6",
    flex: 1,         // Take remaining space inside the panel
    overflowY: "auto", // Scroll independently if text flows long
    border: "1px solid #1e293b",
  },
  fieldBlock: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    backgroundColor: "#1e293b",
    padding: "1rem",
    borderRadius: "8px",
    border: "1px solid #334155",
    flexShrink: 0,
  },
  labelRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  fieldLabel: {
    fontSize: "0.85rem",
    fontWeight: 700,
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  baselineBadge: {
    fontSize: "0.7rem",
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    color: "#10b981",
    padding: "0.15rem 0.4rem",
    borderRadius: "4px",
    border: "1px solid rgba(16, 185, 129, 0.2)",
    fontWeight: 600,
  },
  versionRow: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
  },
  versionLabelRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontSize: "0.75rem",
    fontWeight: 600,
    color: "#64748b",
  },
  staticVal: {
    backgroundColor: "#020617",
    color: "#cbd5e1",
    padding: "0.6rem",
    borderRadius: "4px",
    fontSize: "0.9rem",
    lineHeight: "1.5",
    border: "1px solid #1e293b",
  },
  inputVal: {
    backgroundColor: "#020617",
    color: "#f8fafc",
    padding: "0.6rem",
    borderRadius: "4px",
    fontSize: "0.9rem",
    lineHeight: "1.5",
    border: "1px solid #3b82f6",
    outline: "none",
    fontFamily: "inherit",
    width: "100%",
    boxSizing: "border-box",
  },
  selectVal: {
    backgroundColor: "#020617",
    color: "#f8fafc",
    padding: "0.6rem",
    borderRadius: "4px",
    fontSize: "0.9rem",
    border: "1px solid #3b82f6",
    outline: "none",
    width: "100%",
  },
  centerState: {
    textAlign: "center",
    padding: "4rem 2rem",
    backgroundColor: "#0f172a",
    borderRadius: "12px",
    border: "1px solid #1e293b",
    color: "#94a3b8",
  },
};